Vagrant.configure('2') do |config|
	config.vm.box = 'ubuntu/focal64'
	config.vm.network "private_network", ip: '192.168.56.11'
	config.vm.provider "virtualbox" do |vb|
	 
	  vb.cpus = 2
	  vb.memory = 2048
	  vb.gui=false
	end
      
	config.vm.provision "shell", inline: <<-SHELL
	  wget https://apt.puppetlabs.com/puppet8-release-focal.deb -O puppet.deb
	  sudo dpkg -i puppet.deb
	  sudo apt-get update
	SHELL
      
	# Wp VM (Puppet Agent)
	config.vm.define "puppetaux" do |puppet_aux|
	  puppet_aux.vm.hostname = "puppetaux"
	  puppet_aux.vm.network "forwarded_port", guest: 8082, host: 1234
	  puppet_aux.vm.provision "shell", inline: <<-SHELL
	    sudo echo "192.168.56.10 puppet-main" >> /etc/hosts
	    echo "sudo /opt/puppetlabs/bin/puppet agent --test" >> update.sh
	    sudo chmod +x update.sh
	    sudo apt-get install -y puppet-agent
	    sudo /opt/puppetlabs/bin/puppet config set server puppet-main --section main
	    sudo /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true
	  SHELL
	end
      end
      