Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'
  

  
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
    vb.gui=false
  end

  config.vm.provision "shell", inline: <<-SHELL
  wget https://apt.puppetlabs.com/puppet8-release-focal.deb -O puppet.deb

  sudo dpkg -i puppet.deb
  sudo apt-get update
  SHELL

  config.vm.define "puppet_main", primary: true do |main_config|
    main_config.vm.hostname = 'puppetmain'
    main_config.vm.network "private_network", ip: '192.168.56.10'
    main_config.vm.provision "file", source: "./wp.pp", destination: "$HOME/wp.pp"
    main_config.vm.provision "shell", inline: <<-SHELL
      sudo echo "sudo cp wp.pp /etc/puppetlabs/code/environments/production/manifests" >> config.sh
      sudo chmod +x config.sh
      sudo apt-get install -y puppetserver
      sudo sed -i 's/-Xms2g -Xmx2g/-Xms512m -Xmx512m/g' /etc/default/puppetserver
      sudo echo "*" >> /etc/puppetlabs/puppet/autosign.conf
      sudo /opt/puppetlabs/bin/puppet config set server puppet_main --section main
      sudo systemctl start puppetserver
      sudo systemctl status puppetserver
      sudo systemctl enable puppetserver
      sudo /opt/puppetlabs/bin/puppet module install puppet-archive --version 4.6.0
      sudo /opt/puppetlabs/bin/puppet module install puppetlabs-accounts
      sudo /opt/puppetlabs/bin/puppet module install puppetlabs-mysql
      sudo /opt/puppetlabs/bin/puppet module install puppetlabs-apache
      sudo /opt/puppetlabs/bin/puppet module install adullact-wordpress
      ./config.sh
    SHELL
  end
end

