Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.provision "shell", inline: <<-SHELL
	  sudo apt-get update && sudo apt-get install -y puppet git
	  sudo puppet module install puppetlabs-apache
	  sudo puppet module install puppetlabs-mysql
	  sudo puppet module install puppetlabs-php
	  sudo puppet module install puppetlabs-concat
	  sudo puppet module install puppetlabs-git
	  sudo puppet module install puppetlabs-wordpress
	  sudo puppet apply --modulepath=/etc/puppet/modules /vagrant/manifests/site.pp
	SHELL
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "forwarded_port", guest: 3306, host: 33060
	config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/"]
      end